<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class History extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('history', function (Blueprint $table) {
            $table->id(); 
            $table->string('ident_sexo',4)->nullable();
            $table->string('ident_noExp',12)->nullable();
            $table->string('ident_estaCivil',4)->nullable();
            $table->string('ident_ocupacion',30)->nullable();
            $table->string('antece_fam_diabetes',4)->nullable();
            $table->string('antece_fam_diabetes_descripcion',30)->nullable();
            $table->string('antece_fam_hiv_sida',4)->nullable();
            $table->string('antece_fam_obesidad',4)->nullable();
            $table->string('antece_fam_asma',4)->nullable();
            $table->string('antece_fam_hipertension',4)->nullable();
            $table->string('antece_fam_descripcion_hipertension',4)->nullable();
            $table->string('antece_fam_cancer',4)->nullable();
            $table->string('antece_fam_av_cerebral',4)->nullable();
            $table->string('antece_fam_nerviosos',4)->nullable();
            $table->string('antece_fam_cardiopatias',4)->nullable();
            $table->string('antece_fam_descripcion_cardiopatias',30)->nullable();
            $table->string('antece_fam_toxicomanias',4)->nullable();
            $table->string('antece_fam_tuberculosis',4)->nullable();
            $table->string('antece_fam_otros',20)->nullable();
            $table->string('antece_fam_sifilis',4)->nullable();
            $table->string('antece_pato_info_resp_agudas',4)->nullable();
            $table->string('antece_pato_info_resp_agudas_descripcion',30)->nullable();
            $table->string('antece_pato_hipertension_art',4)->nullable();
            $table->string('antece_pato_asma',4)->nullable();
            $table->string('antece_pato_diabetes_mellitus',4)->nullable();
            $table->string('antece_pato_enf_diarreica',4)->nullable();
            $table->string('antece_pato_enf_diarreica_descripcion',30)->nullable();
            $table->string('antece_pato_av_cerebral',4)->nullable();
            $table->string('antece_pato_parasitosis',4)->nullable();
            $table->string('antece_pato_i_miocardio',4)->nullable();
            $table->string('antece_pato_dengue',4)->nullable();
            $table->string('antece_pato_dengue_descripcion',30)->nullable();
            $table->string('antece_pato_trombo_flebitis',4)->nullable();
            $table->string('antece_pato_tuberculosis',4)->nullable();
            $table->string('antece_pato_quirurgicas',4)->nullable();
            $table->string('antece_pato_artritis',4)->nullable();
            $table->string('antece_pato_artritis_descripcion',30)->nullable();
            $table->string('antece_pato_enf_exantemticas',4)->nullable();
            $table->string('antece_pato_alergias',4)->nullable();
            $table->string('antece_pato_otros',20)->nullable();
            $table->string('antece_no_patolog_tabaco',4)->nullable();
            $table->string('antece_no_patolog_tabaco_descripcion',30)->nullable();
            $table->string('antece_no_patolog_alcohol',4)->nullable();
            $table->string('antece_no_patolog_alimentacion',4)->nullable();
            $table->string('antece_no_patolog_alimentacion_descripcion',30)->nullable();
            $table->string('antece_no_patolog_trabajo',4)->nullable();
            $table->string('antece_no_patolog_gine_tipo_G',4)->nullable();
            $table->string('antece_no_patolog_gine_tipo_P',4)->nullable();
            $table->string('antece_no_patolog_gine_tipo_C',4)->nullable();
            $table->string('antece_no_patolog_gine_tipo_A',4)->nullable();
            $table->string('antece_no_patolog_vivienda',4)->nullable();
            $table->string('antece_no_patolog_vivienda_descripcion',30)->nullable();
            $table->string('antece_no_patolog_fuma_P',4)->nullable();
            $table->string('antece_no_patolog_fuma_C',4)->nullable();
            $table->string('antece_no_patolog_fuma_A',4)->nullable();
            $table->string('antece_no_patolog_medicamento',4)->nullable();
            $table->string('antece_no_patolog_recreacion',4)->nullable();
            $table->string('antece_no_patolog_recreacion_descripcion',30)->nullable();
            $table->string('antece_no_patolog_otro',20)->nullable();
            $table->string('padecimiento_actial_1',50)->nullable();

            $table->string('interro_cabeza_cefalea',2)->nullable();
            $table->string('interro_cabeza_descripcion',30)->nullable();
            $table->string('interro_ojos_descripcion',30)->nullable();
            $table->string('interrogatrio_nariz_descripcion',30)->nullable();
            $table->string('interro_cabeza_vertigos',2)->nullable();
            $table->string('interro_diges_apetito',2)->nullable();
            $table->string('interro_diges_eructos',2)->nullable();
            $table->string('interro_cabeza_mareos',2)->nullable();
            $table->string('interro_cabeza_lipotimias',2)->nullable();
            $table->string('interro_diges_masticacion',2)->nullable();
            $table->string('interro_diges_pirosis',2)->nullable();
            $table->string('interro_ojos_vision',2)->nullable();
            $table->string('interro_ojos_lentes',2)->nullable();
            $table->string('interro_diges_disfagia',2)->nullable();
            $table->string('interro_diges_nausea',2)->nullable();
            $table->string('interro_ojos_congestion',2)->nullable();
            $table->string('interro_ojos_dolor',2)->nullable();
            $table->string('interro_diges_meteorismo',2)->nullable();
            $table->string('interro_diges_habitoIntest',2)->nullable();
            $table->string('interro_nariz_secrecion',2)->nullable();
            $table->string('interro_nariz_obstruccion',2)->nullable();
            $table->string('interro_diges_laxantes',2)->nullable();
            $table->string('interro_diges_hemorroides',2)->nullable();
            $table->string('interro_nariz_senos',2)->nullable();
            $table->string('interro_nariz_epitasis',2)->nullable();
            $table->string('interro_diges_vomitos',2)->nullable();
            $table->string('interro_diges_dolor',2)->nullable();
            $table->string('interro_boca_dientes',2)->nullable();
            $table->string('interro_boca_protesis',2)->nullable();
            $table->string('interro_boca_1_descripcion',2)->nullable();
            $table->string('interro_diges_ictericia',2)->nullable();
            $table->string('interro_diges_evacuacion',2)->nullable();
            $table->string('interro_boca_lengua',2)->nullable();
            $table->string('interro_boca_encias',2)->nullable();
            $table->string('interro_urinario_miccion',2)->nullable();
            $table->string('interro_urinario_incontinencia',2)->nullable();
            $table->string('interro_boca_sabor',2)->nullable();
            $table->string('interro_boca_halitosis',2)->nullable();
            $table->string('interro_boca_2_descripcion',2)->nullable();
            $table->string('interro_urinario_polaquiuria',2)->nullable();
            $table->string('interro_urinario_nicturia',2)->nullable();
            $table->string('interro_cuello_dolor_faringe',2)->nullable();
            $table->string('interro_cuello_movilidad',2)->nullable();
            $table->string('interro_urinario_caract_orina',2)->nullable();
            $table->string('interro_urinario_poliuria',2)->nullable();
            $table->string('interro_cuello_disfonia',2)->nullable();
            $table->string('interro_cuello_adenopatia',2)->nullable();
            $table->string('interro_cuello_descripcion',2)->nullable();
            $table->string('interro_urinario_disuria',2)->nullable();
            $table->string('interro_urinario_hematuria',2)->nullable();
            $table->string('interro_cuello_dolor_cern',2)->nullable();
            $table->string('interro_cuello_tiroides',2)->nullable();
            $table->string('interro_genital_fem_menarca',2)->nullable();
            $table->string('interro_genital_fem_menst',2)->nullable();
            $table->string('interro_cardioRes_tos',2)->nullable();
            $table->string('interro_cardioRes_dolorTorax',2)->nullable();
            $table->string('interro_cardioRes_descripcion_1',2)->nullable();
            $table->string('interro_genital_fem_fUltimaRegla',2)->nullable();
            $table->string('interro_genital_fem_secrecion',2)->nullable();
            $table->string('interro_cardioResp_expectorar',2)->nullable();
            $table->string('interro_cardResp_precordial',2)->nullable();
            $table->string('interro_genital_fem_abortos',2)->nullable();
            $table->string('interro_genital_fem_menopausia',2)->nullable();
            $table->string('interro_cardioResp_hemoptisis',2)->nullable();
            $table->string('interro_cardioResp_opresion',2)->nullable();
            $table->string('interro_cardioResp_descripcion_2',2)->nullable();
            $table->string('interro_genital_fem_hemorragia',2)->nullable();
            $table->string('interro_cardioResp_palpitacion',2)->nullable();
            $table->string('interro_cardioResp_disnea',2)->nullable();
            $table->string('interro_genital_fem_sClimaterio',2)->nullable();
            $table->string('interro_genital_fem_partos',2)->nullable();
            $table->string('interro_cardioResp_cianosis',2)->nullable();
            $table->string('interro_cardioResp_edema',2)->nullable();
            $table->string('interro_cardioResp_descripcion_3',30)->nullable();
            $table->string('interro_genital_masc_potencia',2)->nullable();
            $table->string('interro_genital_masc_relSexuales',2)->nullable();
            $table->string('interro_genital_masc_eyaculacion',2)->nullable();
            $table->string('interro_genital_masc_escurrimiento',2)->nullable();
            $table->string('interro_genital_fem_dismenorrea',2)->nullable();
            $table->string('exp_peso',4)->nullable();
            $table->string('exp_estatura',4)->nullable();
            $table->string('exp_ta',4)->nullable();
            $table->string('exp_pulso',4)->nullable();
            $table->string('expl_fisic_cara',4)->nullable();
            $table->string('expl_fisic_pupilas',4)->nullable();
            $table->string('expl_fisic_cabeza_desc1',30)->nullable();
            $table->string('expl_fisic_forma',4)->nullable();
            $table->string('expl_fisic_dolor',4)->nullable();
            $table->string('expl_fisic_exoftalmo',4)->nullable();
            $table->string('expl_fisic_protesis',4)->nullable();
            $table->string('expl_fisic_movRes',4)->nullable();
            $table->string('expl_fisic_apex',4)->nullable();
            $table->string('expl_fisic_cornea',4)->nullable();
            $table->string('expl_fisic_amigdalas',4)->nullable();
            $table->string('expl_fisic_cabeza_desc2',30)->nullable();
            $table->string('expl_fisic_sonoridad',4)->nullable();
            $table->string('expl_fisic_areac',4)->nullable();
            $table->string('expl_fisic_dientes',4)->nullable();
            $table->string('expl_fisic_parpados',4)->nullable();
            $table->string('expl_fisic_gland_mamaria',4)->nullable();
            $table->string('expl_fisic_tonos_card',4)->nullable();
            $table->string('expl_fisic_lengua',4)->nullable();
            $table->string('expl_fisic_conjuntivas',4)->nullable();
            $table->string('expl_fisic_cabeza_desc3',30)->nullable();
            $table->string('expl_fisic_ruidos_resp',4)->nullable();
            $table->string('expl_fisic_ruidos_agrega',4)->nullable();
            $table->string('expl_fisic_ictericia',4)->nullable();
            $table->string('expl_fisic_reflejos',4)->nullable();
            $table->string('expl_fisic_baso',4)->nullable();
            $table->string('expl_fisic_movilidad',4)->nullable();
            $table->string('expl_fisic_encias',4)->nullable();
            $table->string('expl_fisic_cabeza_desc4',30)->nullable();
            $table->string('expl_fisic_circ_colater',4)->nullable();
            $table->string('expl_fisic_rinones',4)->nullable();
            $table->string('expl_fisic_tiroides',4)->nullable();
            $table->string('expl_fisic_pared',4)->nullable();
            $table->string('expl_fisic_velloPub',4)->nullable();
            $table->string('expl_fisic_carotidas',4)->nullable();
            $table->string('expl_fisic_tonoMusc',4)->nullable();
            $table->string('expl_fisic_cuello_desc1',30)->nullable();
            $table->string('expl_fisic_tono',4)->nullable();
            $table->string('expl_fisic_tumoraciones',4)->nullable();
            $table->string('expl_fisic_yogulares',4)->nullable();
            $table->string('expl_fisic_hernias',4)->nullable();
            $table->string('expl_fisic_meteorismo',4)->nullable();
            $table->string('expl_fisic_ganglios',4)->nullable();
            $table->string('expl_fisic_cuello_desc2',30)->nullable();
            $table->string('expl_fisic_ascitis',4)->nullable();
            $table->string('expl_fisic_higado',4)->nullable();
            $table->string('expl_fisic_adenopatias',4)->nullable();
            $table->string('expl_fisic_formaHombro',4)->nullable();
            $table->string('expl_fisic_movilidad2',30)->nullable();
            $table->string('expl_fisic_cuello_desc3',30)->nullable();
            $table->string('expl_fisic_desviaciones',4)->nullable();
            $table->string('expl_fisic_dolor2',4)->nullable();
            $table->string('expl_fisic_axilas',4)->nullable();
            $table->string('expl_fisic_articulaciones',4)->nullable();
            $table->string('expl_fisic_movilidad3',4)->nullable();
            $table->string('expl_fisic_tonoMus',4)->nullable();
            $table->string('expl_fisic_vello',4)->nullable();
            $table->string('expl_fisic_arterias',4)->nullable();
            $table->string('expl_fisc_musup_desc1',30)->nullable();
            $table->string('expl_fisic_ganglios2',4)->nullable();
            $table->string('expl_fisic_manos',4)->nullable();
            $table->string('expl_fisic_temperatura',4)->nullable();
            $table->string('expl_fisic_sudoracion',4)->nullable();
            $table->string('expl_fisic_msup_desc2',4)->nullable();
            $table->string('expl_fisic_forma2',4)->nullable();
            $table->string('expl_fisic_dolor3',4)->nullable();
            $table->string('expl_fisic_movilidad4',4)->nullable();
            $table->string('expl_fisic_forma4',4)->nullable();
            $table->string('expl_fisic_dolor4',4)->nullable();
            $table->string('tx_1',30)->nullable();
            $table->string('tratamiento',30)->nullable();
            $table->string('patient',4)->nullable();
            $table->string('ident_fecha',12)->nullable();
            $table->timestamps();



        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('history');
    }
}
